language: php
php:
  - 5.6
  - 7
  - nightly

env:
  - LIBEVENT_ENABLED=true
  - LIBEVENT_ENABLED=false

before_install:
  - chmod +x ./scripts/install-libevent.sh
  - chmod +x ./scripts/install-libevent-extension.sh
  - chmod +x ./scripts/run-tests.sh

install:
  - if [[ "$LIBEVENT_ENABLED" == "true" ]]; then ./scripts/install-libevent.sh; fi
  - if [[ "$LIBEVENT_ENABLED" == "true" ]]; then ./scripts/install-libevent-extension.sh; fi

before_script:
  - composer install

script:
  - ./scripts/run-tests.sh
  - phpunit
