language: php
php:
  - 5.6
  - 7
  - nightly

env:
  - LIBEVENT_ENABLED=true
  - LIBEVENT_ENABLED=false

before_script:
  - composer install
  - echo extension=mongo.so >> ./libevent.ini
  - chmod +x ./run-tests.sh

script:
  - ./run-tests.sh
  - phpunit

after_script:
  - rm ./libevent.ini
