language: php
php:
  - 5.6
  - 7
  - nightly

env:
  - LIBEVENT_DISABLED=true
  - LIBEVENT_DISABLED=false

before_script:
  - composer install
  - if ["$LIBEVENT_DISABLED" = false]; then phpenv config-rm xdebug.ini && phpunit tests/CreateStreamSelectLoopTest.php else phpunit tests/CreateLibEventLoopTest.php fi